# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'watchDemo-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!
  pod 'iOSDFULibrary'#, '~> 4.11.1'
  pod 'FMDB'
  pod 'AFNetworking'#, '~> 4.0'
  pod 'MJExtension'

end
